SELECT child.ITEM_ID, child.ITEM_NAME, child.RARITY
FROM ITEM_INFO child
LEFT JOIN ITEM_TREE parent
ON child.ITEM_ID = parent.PARENT_ITEM_ID
WHERE parent.PARENT_ITEM_ID IS NULL
ORDER BY child.ITEM_ID DESC
