SELECT COUNT(fi.FISH_TYPE) AS FISH_COUNT, fn.FISH_NAME as FISH_NAME
FROM FISH_INFO fi
LEFT JOIN FISH_NAME_INFO fn
ON fi.FISH_TYPE = fn.FISH_TYPE
GROUP BY fi.FISH_TYPE, fn.FISH_NAME
ORDER BY FISH_COUNT DESC;