WITH CTE AS (
    SELECT EMP_NO,
        (CASE
            WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 THEN 'A'
            WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C' END) AS GRADE,
        (CASE
            WHEN AVG(SCORE) >= 96 THEN 0.2
            WHEN AVG(SCORE) >= 90 THEN 0.15
            WHEN AVG(SCORE) >= 80 THEN 0.1
        ELSE 0 END) AS cal
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT CTE.EMP_NO, e.EMP_NAME, CTE.GRADE, CTE.cal*e.SAL AS BONUS
FROM CTE LEFT JOIN HR_EMPLOYEES e ON CTE.EMP_NO=e.EMP_NO
