SELECT 
    CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID, FILE_NAME,FILE_EXT) AS FILE_PATH
FROM (
    SELECT b.FILE_ID, b.FILE_EXT, b.FILE_NAME, b.BOARD_ID,
    DENSE_RANK () OVER (ORDER BY a.VIEWS DESC) AS view_rnk
    FROM USED_GOODS_BOARD a
    LEFT JOIN USED_GOODS_FILE b
    ON a.BOARD_ID = b.BOARD_ID
) CTE
WHERE view_rnk = 1
ORDER BY FILE_ID DESC;