-- 1. 길이 30cm 이상
-- 2. 조건 분류

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM(SELECT ID, FISH_TYPE, COALESCE(LENGTH, 10) AS LENGTH, TIME FROM FISH_INFO) cte
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE
